server:
  port: 8081


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/live?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 422817618
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 512MB
      max-request-size: 512MB
#    database-platform: org.hibernate.dialect.MySQLDialect
redis:
  database: 0
  host: localhost
  port: 6379
  password:
  jedis:
    pool:
      max-active: 100
      max-idle: 10
      max-wait: 10000
  timeout: 5000



liveDance:
  file:
    uploadpath:  /static/uploadfiles/
  bizId: 76466
  key:
  playUrl: live.hexurong.xyz/live/